import = [
  # "./themes/everforest_dark.toml",
  # "~/.config/alacritty/macOS.toml",
  # "./windows.toml"
  "~/AppData/Roaming/alacritty/themes/everforest_dark.toml",
  "~/AppData/Roaming/alacritty/windows.toml"
]

[env]
TERM = 'alacritty'


[keyboard]
bindings = [
{action = "SpawnNewInstance", mods = "Control", key = "n"},
{action = "ToggleFullscreen", mods = "Control", key = "f"},
{action = "IncreaseFontSize", mods = "Control", key = "="},
{action = "DecreaseFontSize", mods = "Control", key = "-"},
{action = "ResetFontSize", mods = "Control", key = "0"}
]
